version: '3'

services:

  mara-postgres:
    container_name: mara-postgres
    image: mara-postgres:dev
    build: ./.scripts/docker/postgres/
    ports:
      - 5432:5432
    volumes:
      - "mara-postgres_data:/var/lib/postgresql/data"

  mara-app:
    container_name: mara-app
    image: mara-app:dev
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./:/mara
    depends_on:
      - mara-postgres
    stdin_open: true
    tty: true

volumes:
    mara-postgres_data:
        driver: "local"

